spring.application.name=security-service

########################################
# Database Configuration
########################################
spring.datasource.url=jdbc:postgresql://${DB_HOST:db}:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true


########################################
# JPA Configuration
########################################
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=theshikanavod@gmail.com
spring.mail.password=qqig plgf uvyc nkxo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=theshikanavod@gmail.com


jwt.secret=e8C7y/8rYFvXokm3h4yx1NnTu7Eddk1LMZ4XscKfDcXKGuTfyDsvWgL5GqprbR8cJlI2zIZsRZbyE1zYDL4xXQ==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

///########################################
# for development purposes only
########################################
admin.default.email=${ADMIN_EMAIL}
admin.default.password=${ADMIN_PASSWORD}
admin.auto-create=${ADMIN_AUTO_CREATE}