spring.application.name=reservation-service

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.cloud.gcp.sql.database-name=${DB_NAME}

# GCP
spring.cloud.gcp.sql.instance-connection-name=${DB_INSTANCE_CONNECTION_NAME}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
