spring.application.name=reservation-service

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.cloud.gcp.sql.database-name=${DB_NAME}

# GCP
spring.cloud.gcp.sql.instance-connection-name=${DB_INSTANCE_CONNECTION_NAME}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.kafka.producer.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

app.kafka.topic.notification=reservation.confirmed.events
app.kafka.topic.stall-update=stall.status.update

spring.security.oauth2.resourceserver.jwt.issuer-uri=${JWT_ISSUER_URI:http://security-service:8081}

stall.service.url=${STALL_SERVICE_URL:http://stall-service:8080/api/stalls}